spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    path match:
      matching-strategy: ant_path_matcher